/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * 移动云盘配置
 */
export interface Config {
  /**
   * cookie authorization 字段
   */
  token: string;
  /**
   * 手机号
   */
  phone: string;
  /**
   * auth_token
   */
  auth?: string;
  /**
   * 摇一摇
   */
  shake?: {
    /**
     * 是否开启该功能
     */
    enable?: boolean;
    /**
     * 摇一摇次数
     */
    num?: number;
    /**
     * 每次间隔时间（秒）
     */
    delay?: number;
    [k: string]: unknown;
  };
  /**
   * 果园
   */
  garden?: {
    /**
     * 是否开启该功能
     */
    enable?: boolean;
    [k: string]: unknown;
  };
  [k: string]: unknown;
}
